# Generated by Django 5.2.6 on 2025-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, choices=[('architect', 'Architect'), ('interior_designer', 'Interior Designer'), ('brand_marketing', 'Brand/Marketing'), ('developer', 'Developer'), ('other', 'Other')], max_length=50)),
                ('project_location', models.CharField(blank=True, max_length=255)),
                ('project_type', models.CharField(blank=True, choices=[('retail_fit_out', 'Retail fit-out'), ('fnb_restaurant', 'F&B / Restaurant'), ('office_interior', 'Office interior'), ('residential', 'Residential'), ('hospitality', 'Hospitality'), ('other', 'Other')], max_length=50)),
                ('start_timeline', models.CharField(blank=True, choices=[('immediately', 'Immediately'), ('within_1_month', 'Within 1 month'), ('one_to_three_months', '1-3 months'), ('three_to_six_months', '3-6 months'), ('six_plus_months', '6+ months'), ('just_exploring', 'Just exploring')], max_length=50)),
                ('project_brief', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
